### ISSUE TITLE
Teal folders

### ISSUE THREAD

**Issue by irondave** [ozonos/ozon-icon-theme-folders#1]
Can you make the teal theme for folders? please?

**Comment by me4oslav** [comment]
I guess. How does this look?
![teal](https://cloud.githubusercontent.com/assets/1658870/6310082/f6e3eba2-b95b-11e4-8b3e-9767535d5787.png)

**Comment by irondave** [comment]
really gorgeous!!!

**Comment by me4oslav** [comment]
Now you wait for @cldx to add them.

**Comment by cldx** [comment]
Teal Folders have been added in facb91dd28e21ae6b4b0a55187eeeebe9fc0fcbb
