### ISSUE TITLE
Teal Folder Directory Has Incorrect Permissions After Install

### ISSUE THREAD

**Issue by matt-della** [ozonos/ozon-icon-theme-folders#3]
After running `make install` as root, these are the permissions on the Ozon icons in /usr/share/icons/. The teal icon theme cannot be applied correctly because of this. 

```
drwxr-xr-x   6 root root 4096 Feb 20 13:13 Ozon
drwxr-xr-x   4 root root 4096 Feb 21 15:05 Ozon-Amber
drwxr-xr-x   4 root root 4096 Feb 21 15:05 Ozon-Blue
drwxr-xr-x   4 root root 4096 Feb 21 15:05 Ozon-Brown
drwxr-xr-x   4 root root 4096 Feb 21 15:05 Ozon-Green
drwxr-xr-x   4 root root 4096 Feb 21 15:05 Ozon-Grey
drwxr-xr-x   4 root root 4096 Feb 21 15:05 Ozon-Orange
drwxr-xr-x   4 root root 4096 Feb 21 15:05 Ozon-Purple
drwxr-xr-x   4 root root 4096 Feb 21 15:05 Ozon-Red
drwx------   4 root root 4096 Feb 21 15:04 Ozon-Teal

```

**Comment by cldx** [comment]
I'm not quite sure what caused this. The only thing i found was that the Makefile was missing the Teal Folder i'm gonna commit this ( 6f5243ccfee56a94a059b3202cb1a999903c6d23 ) and maybe it will fix the issue.

You probably will have to try to reinstall, as in 'make uninstall' and first check if it removed all the Colored Folders from  /usr/share/icons, then install again with the updated Makefile

**Comment by cldx** [comment]
Okay, now wait, i just noticed i messed up the install-paths alltogether, give me a minute to check this. I'll commit an updated Makefile in a couple of minutes.

**Comment by cldx** [comment]
Okay now it should cleanly (un)install everything if you use the Makefile from the latest commit ( 0e914d92f78bedc5611ec3fc0eced9232eb8cf71 ). First, do 'make uninstall' and then check if the Teal Folder was also removed from /usr/share/icons/ (just to make sure), then just reinstall with make install.
